### linear algrebra

NumPy adalah package array tujuan umum. Ini menyediakan objek array multidimensi berkinerja tinggi, dan alat untuk bekerja dengan array ini. Ini adalah standard package untuk komputasi ilmiah dengan Python. Numpy pada dasarnya digunakan untuk membuat array n dimensi.

In [1]:
import numpy as np

A = [[1, 3, 5], [7, 12, 21], [5, 18, 3]]
B = [13, 123, 52]

# linalg.solve to solve a linear matrix equation or system of linear scalar equations
np.linalg.solve(A, B) 

array([23.6375    , -3.69166667,  0.0875    ])

### Vektor

Vektor dibangun dari komponen, yang merupakan bilangan biasa. Kita dapat menganggap vektor sebagai daftar bilangan, dan aljabar vektor sebagai operasi yang dilakukan pada bilangan dalam daftar. Dengan kata lain vektor adalah array 1-D numpy.

In [4]:
# Horizontal Vector

# creating list  
list1 = [10, 20, 30, 40, 50]  

# Creating 1-D Horizontal Array  
vtr = np.array(list1) 
 
print("We create a vector from a list: ", vtr)  

We create a vector from a list:  [10 20 30 40 50]


In [6]:
# Vertical list 

#  creating list
list1 = [[12], [40], [6],[10]]  
  
# Creating 1-D Vertical Array  
vtr = np.array(list1)  

print("We create a vector from a list: \n", vtr)  

We create a vector from a list: 
 [[12]
 [40]
 [ 6]
 [10]]


Below is the list of basic operations that we can perform in vector.

    Arithmetic
    Subtraction
    Multiplication
    Division
    Dot Product
    Scalar Multiplications

In [7]:
#Addition of 2 vector

list1 = [10,20,30,40,50] # horizontal list
list2 = [11,12,13,14,15]    
   
vtr1 = np.array(list1)   
vtr2= np.array(list2)   
  
print("We create vector from a list 1: ", vtr1)   
print("We create vector from a list 2: ", vtr2)   
   
vctr_add = vtr1 + vtr2  
print("Addition of two vectors: ", vctr_add)  

We create vector from a list 1:  [10 20 30 40 50]
We create vector from a list 2:  [11 12 13 14 15]
Addition of two vectors:  [21 32 43 54 65]


In [8]:
#Substraction 

list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)   
vtr2 = np.array(list2)   
   
print("We create vector from a list 1: ", vtr1)   
print("We create vector from a list 2: ", vtr2)   
  
vtr_sub = vtr1 - vtr2  
print("Subtraction of two vectors: ", vtr_sub)  

We create vector from a list 1:  [10 20 30 40 50]
We create vector from a list 2:  [5 2 4 3 1]
Subtraction of two vectors:  [ 5 18 26 37 49]


In [9]:
#multiplication

list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)      
vtr2= np.array(list2)   
   
print("We create vector from a list 1: ", vtr1)   
print("We create vector from a list 2: ", vtr2)   
  
vtr_mul = vtr1 * vtr2  
print("Multiplication of two vectors: ", vtr_mul)  

#Multiplication didapat dari : 
#vct[0] = x[0] * y[0]
#vct[1] = x[1] * y[1]

We create vector from a list 1:  [10 20 30 40 50]
We create vector from a list 2:  [5 2 4 3 1]
Multiplication of two vectors:  [ 50  40 120 120  50]


In [10]:
#Division of 2 vector
list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)  
vtr2 = np.array(list2)   
   
print("We create vector from a list 1: ", vtr1)   
print("We create vector from a list 2: ", vtr2)  
  
vtr_div = vtr1 / vtr2  
print("Division of two vectors: ", vtr_div) 

We create vector from a list 1:  [10 20 30 40 50]
We create vector from a list 2:  [5 2 4 3 1]
Division of two vectors:  [ 2.         10.          7.5        13.33333333 50.        ]


In [11]:
# Vector Dot Product
# The vector dot product performs between the two same-length sequential vectors and returns the single dot product. 
# We will use the .dot() method to perform the dot product 
# vector c = x . y = (x1 * y1 + x2 * y2) 

list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)    
vtr2= np.array(list2)   
   
print("We create vector from a list 1: ", vtr1)   
print("We create vector from a list 2: ", vtr2) 
  
vtr_product = vtr1.dot(vtr2)  
print("Dot product of two vectors: ",vtr_product)  

We create vector from a list 1:  [10 20 30 40 50]
We create vector from a list 2:  [5 2 4 3 1]
Dot product of two vectors:  380


In [12]:
# Vector scalar
# we multiply the scalar with the each component of the vector

list1 = [10,20,30,40,50]   
vtr1 = np.array(list1)   
scalar_value = 5  
       
print("We create vector from a list 1: ", vtr1)   
      
# printing scalar value   
print("Scalar Value  : " + str(scalar_value))   
       
vtr_scalar = vtr1 * scalar_value  
print("Multiplication of two vectors: ", vtr_scalar)  

We create vector from a list 1:  [10 20 30 40 50]
Scalar Value  : 5
Multiplication of two vectors:  [ 50 100 150 200 250]


### Projection Vector

In [14]:
u = np.array([1, 2, 3]) # vector u, horizontal vector
v = np.array([5, 6, 2]) # vector v, horizontal vector

# Task: Project vector u on vector v

# finding norm of the vector v
v_norm = np.sqrt(sum(v ** 2))

# finding norm of the vector u
u_norm = np.sqrt(sum(u ** 2))

# Apply the formula as mentioned above
# for projecting a vector onto another vector
# find dot product using np.dot()
proj_of_u_on_v = (np.dot(u, v) / v_norm ** 2) * v
print("Projection of Vector u on Vector v is: ", proj_of_u_on_v)

proj_of_v_on_u = (np.dot(u, v) / u_norm ** 2) * u
print("Projection of Vector u on Vector v is: ", proj_of_v_on_u)

Projection of Vector u on Vector v is:  [1.76923077 2.12307692 0.70769231]
Projection of Vector u on Vector v is:  [1.64285714 3.28571429 4.92857143]


### Basis

In [15]:
# old vector list
vec_old = [3, 4]

# Standard
w1 = [-2, 4]
w2 = [2, 1]

# new basis
# linalg.inv is used to compute the multiplicative inverse of a matrix
vec_new = np.linalg.inv(np.array([w2,w1])).dot(vec_old)
print(vec_new)

[0.8 1.4]


In [16]:
# old vector list
vec_old = [1,2,3]

# standard
w1 = [1, 0, 0]
w2 = [0, 0, 1]
w3 = [0, 1, 0]

# new basis
# linalg.inv is used to compute the multiplicative inverse of a matrix
vec_new = np.linalg.inv(np.array([w1, w2, w3])).dot(vec_old)
print(vec_new)

[1. 3. 2.]
